// Generated by OpenCode v1.4.0
#include <iostream>
#include <fstream>
#include <string>
#include <vector>
#include <cstdlib>

void listModels() {
    FILE* pipe = popen("opencode models", "r");
    if (!pipe) {
        std::cerr << "Failed to run opencode models" << std::endl;
        exit(1);
    }
    char buffer[256];
    while (fgets(buffer, sizeof(buffer), pipe) != nullptr) {
        std::cout << buffer;
    }
    pclose(pipe);
}

int main(int argc, char* argv[]) {
    std::string model;
    std::string outputFile;
    std::vector<std::string> promptArgs;
    bool showModel = false;

    for (int i = 1; i < argc; ++i) {
        std::string arg = argv[i];
        if (arg == "--list-models" || arg == "-l") {
            listModels();
            return 0;
        } else if (arg == "--model" || arg == "-m") {
            if (i + 1 < argc) {
                model = argv[++i];
            } else {
                std::cerr << "Error: --model requires an argument" << std::endl;
                return 1;
            }
        } else if (arg == "--output" || arg == "-o") {
            if (i + 1 < argc) {
                outputFile = argv[++i];
            } else {
                std::cerr << "Error: --output requires a filename" << std::endl;
                return 1;
            }
        } else if (arg == "--show-model" || arg == "-s") {
            showModel = true;
        } else {
            promptArgs.push_back(arg);
        }
    }

    if (promptArgs.empty()) {
        std::cerr << "Usage: " << argv[0] << " [options] <prompt>" << std::endl;
        std::cerr << "Example: " << argv[0] << " \"How do I reverse a string in Python?\"" << std::endl;
        std::cerr << "Options:" << std::endl;
        std::cerr << "  --list-models, -l       List available models" << std::endl;
        std::cerr << "  --model, -m <model>     Use a specific model (provider/model)" << std::endl;
        std::cerr << "  --output, -o <file>     Save answer to file" << std::endl;
        std::cerr << "  --show-model, -s        Show model name in output" << std::endl;
        return 1;
    }

    std::string prompt;
    for (const auto& word : promptArgs) {
        if (!prompt.empty()) prompt += " ";
        prompt += word;
    }

    std::string cmd = "opencode run";
    if (!model.empty()) {
        cmd += " --model " + model;
    }
    cmd += " " + prompt;

    FILE* pipe = popen((cmd + " 2>&1").c_str(), "r");
    if (!pipe) {
        std::cerr << "Failed to run opencode" << std::endl;
        return 1;
    }

    std::ofstream outFile;
    if (!outputFile.empty()) {
        outFile.open(outputFile);
        if (!outFile) {
            std::cerr << "Failed to open output file: " << outputFile << std::endl;
            pclose(pipe);
            return 1;
        }
    }

    char buffer[256];
    while (fgets(buffer, sizeof(buffer), pipe) != nullptr) {
        std::string line = buffer;
        bool isModelLine = line.find("Using model") == 0 || line.find("Model:") == 0;
        bool isStatusLine = line.find(">") != std::string::npos && line.find("\xC2\xB7") != std::string::npos;
        bool isAnsiLine = line.find("\x1b[") != std::string::npos;
        if (showModel || (!isModelLine && !isStatusLine && !isAnsiLine)) {
            std::cout << buffer;
            if (outFile) {
                outFile << buffer;
            }
        }
    }

    int result = pclose(pipe);
    if (outFile) {
        outFile.close();
    }
    return result;
}
